runtime: python37
#python 3.7
entrypoint: gunicorn -b :$PORT wishlist.wsgi
#command app engine runs to run app

#tells how to route static files 
handlers:
- url: /static
  static_dir: www/static
  # 2 spaces

# how to route everything else
- url: /.*
  script: auto

env_variables:
  MCTC_PASS: lkj987bhu

beta_settings:
  cloud_sql_instances: wishlistdjango:us-central1:wishlistdb
